#!/bin/bash

# Generate a random number between 0 and 1
random_number=$((RANDOM % 2))

sleep 2
# Randomly return success or failure based on the random number
if [ $random_number -eq 0 ]; then
    echo "Returning success"
    exit 0
else
    echo "Returning failure"
    exit 1
fi

