#!/usr/bin/ruby

`git fetch origin refs/notes/*:refs/notes/*`
notes = `git notes list`.split("\n").map { |x| x.split(" ") }

notes.each do |note|
  note_content = `git cat-file -p #{note[0]}`
  puts "--------"
  puts "#{note[0]}: #{note_content}"
  puts "#{note[1]}"
  puts "--------"
end
