#!/usr/bin/ruby

notes = `git notes list`.split("\n").map { |x| x.split(" ") }

notes.each do |note|
  note_content = `git cat-file -p #{note[0]}`
  puts "--------"
  puts "#{note_content}"
  puts "--------"
end
