#!/bin/bash

AUTHOR=${GIT_AUTHOR_EMAIL:-$(git config user.email)}
REF_PATH=refs/notes/ubik/memos/$AUTHOR

NOTE=$(gum write --placeholder "Add a note about your codebase... (CTRL+D to finish)" --width 120)
echo "Publish?"
PUBLISHED=$(gum choose true false)
UUID=$(uuidgen | tr 'A-Z' 'a-z')
ROOT_TREE_OID=$(git show -s --format=%T HEAD)

JSON=$(jq -n -c \
  --arg id "$UUID" \
  --arg title "$PROJECT_TITLE" \
  --arg content "$NOTE" \
  --arg author "$AUTHOR" \
  --arg published "$PUBLISHED" \
  '{
    id: $id,
    type: "note",
    author: $author,
    content: $content,
    published: $published
  }'
)

git notes --ref $REF_PATH append --no-separator -m "$JSON" $ROOT_TREE_OID
git notes --ref $REF_PATH show $ROOT_TREE_OID

exit 0
