#!/bin/bash

REF_PATH=refs/notes/ubik/projects

PROJECT_TITLE=$(gum input --placeholder "Title your project..." --width 120)
PROJECT_DESCRIPTION=$(gum input --placeholder "Describe your project..." --width 120)
UUID=$(uuidgen | tr 'A-Z' 'a-z')
ROOT_TREE_OID=$(git show -s --format=%T HEAD)
AUTHOR="garrett@blvrd.co"

JSON=$(jq -n -c \
  --arg id "$UUID" \
  --arg title "$PROJECT_TITLE" \
  --arg description "$PROJECT_DESCRIPTION" \
  --arg author "$AUTHOR" \
  '{
    id: $id,
    type: "project",
    author: $author,
    data: {
      title: $title,
      description: $description
    }
  }'
)

git notes --ref $REF_PATH append --no-separator -m "$JSON" $ROOT_TREE_OID
git notes --ref $REF_PATH show $ROOT_TREE_OID

exit 0
