#!/bin/bash

REF_PATH=refs/notes/ubik/notes

# List all note refs
note_refs=$(git notes --ref $REF_PATH list)

# Check if there are any note refs
if [ -z "$note_refs" ]; then
    echo "No note refs found in this repository."
    exit 0
fi

# Iterate over each note ref
while read -r line; do
    note_hash=$(echo $line | cut -d ' ' -f2)

    echo "Note Content for $note_hash:"
    git notes --ref $REF_PATH show $note_hash
    echo "-------------------------------------------"
done <<< "$note_refs"

exit 0
