#!/usr/bin/ruby

require "json"
require "securerandom"

ob = {
  type: "bug",
  id: SecureRandom.uuid,
  message: ARGV[0]
}

json = JSON.generate(ob)

oid = `git show -s --format=%T HEAD`

`git notes add -m \"#{json}\" #{oid}`
`git push origin refs/notes/*`
